/*  =========================================================================
    zp - generated layer of public API

    Copyright (c) the Contributors as noted in the AUTHORS file.
    This file is part of ZP, ZeroMQ Piper
    http://githut.com/zmonit/zp

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZP_LIBRARY_H_INCLUDED
#define ZP_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  ZP version macros for compile-time API detection
#define ZP_VERSION_MAJOR 0
#define ZP_VERSION_MINOR 1
#define ZP_VERSION_PATCH 0

#define ZP_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZP_VERSION \
    ZP_MAKE_VERSION(ZP_VERSION_MAJOR, ZP_VERSION_MINOR, ZP_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZP_STATIC
#       define ZP_EXPORT
#   elif defined ZP_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ZP_EXPORT __declspec(dllexport)
#       else
#           define ZP_EXPORT
#       endif
#   elif defined ZP_EXPORTS
#       define ZP_EXPORT __declspec(dllexport)
#   else
#       define ZP_EXPORT __declspec(dllimport)
#   endif
#   define ZP_PRIVATE
#elif defined (__CYGWIN__)
#   define ZP_EXPORT
#   define ZP_PRIVATE
#else
#   define ZP_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZP_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define ZP_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  ZP_BUILD_DRAFT_API
#define ZP_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ZP_BUILD_DRAFT_API
typedef struct _zp_proto_t zp_proto_t;
#define ZP_PROTO_T_DEFINED
typedef struct _zp_server_t zp_server_t;
#define ZP_SERVER_T_DEFINED
#endif // ZP_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ZP_BUILD_DRAFT_API
#include "zp_proto.h"
#include "zp_server.h"
#endif // ZP_BUILD_DRAFT_API

#ifdef ZP_BUILD_DRAFT_API
//  Self test for private classes
ZP_EXPORT void
    zp_private_selftest (bool verbose, const char *subtest);
#endif // ZP_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
